defaults:
  app:
    queueName: null
  pulse:
    username: !env PULSE_USERNAME
    password: !env PULSE_PASSWORD
  taskcluster:
    credentials:
      clientId:     !env TASKCLUSTER_CLIENT_ID
      accessToken:  !env TASKCLUSTER_ACCESS_TOKEN
production:
  app:
    queueName: incoming-stats
